name: MLOps Pipeline

on:
  push:
    branches: [master]
    paths:
      - 'data/**.dvc'
      - 'src/**.py'
      - 'params.yaml'
  workflow_dispatch:

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/ -v


  train:
    name: Train
    needs: test
    runs-on: ubuntu-latest
    outputs:
      accuracy: ${{ steps.read_metrics.outputs.accuracy }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Authenticate to Cloud Storage
        run: |
          echo '${{ secrets.CLOUD_CREDENTIALS }}' > /tmp/sa-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa-key.json" >> $GITHUB_ENV

      - name: Pull data with DVC
        run: dvc pull data/train_phase1.csv.dvc data/eval.csv.dvc

      - name: Train model
        run: python src/train.py

      - name: Read metrics
        id: read_metrics
        run: |
          ACC=$(python -c "import json; d=json.load(open('outputs/metrics.json')); print(d['accuracy'])")
          echo "accuracy=$ACC" >> "$GITHUB_OUTPUT"

      - name: Upload model to Cloud Storage
        run: |
          python - <<'EOF'
          from google.cloud import storage
          client = storage.Client()
          bucket = client.bucket("mlops-lab-bucket-nhanphan-2026")
          blob = bucket.blob("models/latest/model.pkl")
          blob.upload_from_filename("models/model.pkl")
          print("Uploaded model.pkl to GCS")
          EOF

      - name: Save metrics as artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: outputs/metrics.json


  eval:
    name: Eval
    needs: train
    runs-on: ubuntu-latest
    steps:

      - name: Check eval gate
        run: |
          python - <<'EOF'
          acc = float("${{ needs.train.outputs.accuracy }}")
          if acc < 0.70:
              raise SystemExit(f"FAILED: accuracy {acc:.4f} < 0.70. Huy deploy.")
          print("PASSED: dang trien khai model.")
          EOF


  deploy:
    name: Deploy
    needs: eval
    runs-on: ubuntu-latest
    steps:

      - name: SSH deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: phana
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo systemctl restart mlops-serve
            sleep 5
            curl -sf http://localhost:8000/health && echo "Health check passed." || exit 1
